### ISSUE TITLE
Delete LUN problem

### ISSUE THREAD

**Issue by tomcsi** [emc-openstack/vnx-direct-driver#3]
Hi,

If Openstack creating the VM, but the VM timed out, cinder try to remove LUN from EMC, but it's not work.

2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher Traceback (most recent call last):
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py", line 134, in _dispatch_and_reply
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     incoming.message))
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py", line 177, in _dispatch
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py", line 123, in _do_dispatch
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     result = getattr(endpoint, method)(ctxt, **new_args)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 127, in lvo_inner1
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     return lvo_inner2(inst, context, volume_id, **kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/openstack/common/lockutils.py", line 233, in inner
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     retval = f(*args, **kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 126, in lvo_inner2
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     return f(*_args, **_kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 455, in delete_volume
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     {'status': 'error_deleting'})
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/openstack/common/excutils.py", line 82, in __exit__
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     six.reraise(self.type_, self.value, self.tb)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 444, in delete_volume
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     self.driver.delete_volume(volume_ref)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_cli_iscsi.py", line 78, in delete_volume
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     self.cli.delete_volume(volume)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_vnx_cli.py", line 106, in inner
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     ret = func(self, *args, **kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_vnx_cli.py", line 1597, in delete_volume
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     self._client.delete_lun(volume['name'])
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_vnx_cli.py", line 106, in inner
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     ret = func(self, *args, **kwargs)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_vnx_cli.py", line 366, in delete_lun
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher     raise EMCVnxCLICmdError(command_delete_lun, rc, out)
2015-02-11 13:54:35.915 1962 TRACE oslo.messaging.rpc.dispatcher EMCVnxCLICmdError: Bad or unexpected response from the storage volume backend API: EMCVnxCLICmdError : ['lun', '-destroy', '-name', u'volume-be841785-bfb5-49fe-bbca-5df735f0823b', '-forceDetach', '-o'] (Return Code: 156) (Output: [u"Cannot unbind LUN because it's contained in a Storage Group\\n"])

**Comment by vmtyler** [comment]
was the cinder volume created along with the VM?

**Comment by tomcsi** [comment]
Yes, the volume created.

**Comment by vmtyler** [comment]
iSCSI or FC?
What does your cinder.conf look like?
Can you create a instance without a cinder volume and does it work?

**Comment by tomcsi** [comment]
iSCSI

Yes, the vm created without cinder volume.

cinder.conf:
[DEFAULT]
rootwrap_config = /etc/cinder/rootwrap.conf
api_paste_confg = /etc/cinder/api-paste.ini
iscsi_helper = tgtadm
volume_name_template = volume-%s
volume_group = cinder-volumes
verbose = True
auth_strategy = keystone
state_path = /var/lib/cinder
lock_path = /var/lock/cinder
volumes_dir = /var/lib/cinder/volumes
use_syslog=False
api_paste_config=/etc/cinder/api-paste.ini
debug=False
storage_availability_zone=nova
log_dir=/var/log/cinder
osapi_volume_listen=0.0.0.0
osapi_volume_workers=8
default_availability_zone=nova
control_exchange=openstack
amqp_durable_queues=False
rpc_backend=cinder.openstack.common.rpc.impl_kombu
volume_driver=cinder.volume.drivers.emc.emc_cli_iscsi.EMCCLIISCSIDriver
iscsi_ip_address=10.1.5.34
volume_backend_name=DEFAULT
quota_volumes=10
quota_snapshots=10
quota_driver=cinder.quota.DbQuotaDriver
quota_gigabytes=1000
glance_num_retries=0
glance_api_ssl_compression=False
glance_api_insecure=False
glance_api_servers=glance.dc:9292
glance_api_version=2
san_password=admin
naviseccli_path=/opt/Navisphere/bin/naviseccli
max_luns_per_storage_group=256
san_login=admin
san_ip=10.1.3.11
default_timeout=10
storage_vnx_pool_name=Openstack
rabbit_host=rabbitmq.dc
rabbit_userid=openstack
rabbit_use_ssl=False
rabbit_virtual_host=/
rabbit_hosts=rabbitmq.dc:5672
rabbit_ha_queues=False
rabbit_password=xxx
rabbit_port=5672

[database]
idle_timeout=3600
max_retries=10
retry_interval=10
min_pool_size=1
connection=mysql://cinder:xxx@mysql.dc/cinder

**Comment by vmtyler** [comment]
Can you create a volume separately and then attach it to an instance?

**Comment by tomcsi** [comment]
Yes, I can creating and attaching. The problem is the timeout, if nova-compute cannot create to the vm because block volume not ready, cinder try to rollback the volume, but the volume attached to the hypervisor in emc. I think first must deattach from volume from hypervisor in emc before remove.
